---
- name: Pull latest Docker image
  docker_container:
    name: registrationform 
    image: satwik0731/registrationform:v11
    state: started
    restart_policy: always
    ports:
      - "8866:8080"
  become: yes
