---
- name: Deploy OnlineBookstore on Docker Host
  hosts: docker
  become: yes

  tasks:
    - name: Pull latest image
      docker_container:
        name: registrationform
        image: satwik0731/registrationform
        state: started
        restart_policy: always
        ports:
          - "8866:8080"
        recreate: yes
